### ISSUE TITLE
Docs/Examples

### ISSUE THREAD

**Issue by idkjs** [amsross/bs-highland#3]
You dont happen to have any docs,test, examples laying around do you?

It would be much appreciated.

I am trying to figure out the zip function. I have this going in `js` but cant seem to get it in `re`:
```js
var _ = require('highland');
let test = _([
	'a',
	'b',
	'c'
]).zip([
	1,
	2,
	3
]);
test.map(_.log).resume();
```

Thanks for sharing this project.

**Comment by amsross** [comment]
@idkjs I don't have anything in the way of docs or examples and, to be honest, I've made some changes to the versions of this I use in projects that I've been meaning to make here but haven't gotten around to. 

That being said, the signature I've provided is `(t('e, 'a), t('e, 'a)) => t('e, array('a))`, whereas the example you posted above looks more like `(t('e, 'a), array('a)) => t('e, array('a))`. Is it possible that's the issue you're having?

**Comment by idkjs** [comment]
The example is from https://highlandjs.org/#zip so i figured it would work with these bindings. I think I might wait for you to update this repo. This was a learning experiment so I did not need the solution right away. Thank you.

**Comment by amsross** [comment]
I've kind of taken the approach of locking down the signatures of the base functions to be less flexible. It's certainly possible to have `_(arg)` take a node stream, a highland stream, or an array for `arg`, but (IMO) polymorphic functions add more user-land ceremony without adding much value.

re: https://reasonml.chat/t/modeling-a-polymorphic-high-order-callback-parameter/1623
